.PHONY : all clean

all:
	g++ -std=c++11 np_simple.cpp -o np_simple
	g++ -std=c++11 np_single_proc.cpp -o np_single_proc
	g++ -std=c++11 np_multi_proc.cpp -o np_multi_proc


clean:
	rm -rf np_simple.o np_simple
	rm -rf np_single_proc.o np_signle_proc
	rm -rf np_multi_proc.o np_multi_proc

