.PHONY : all clean

all:
	g++ -std=c++11 delayedremovetag.cpp -o delayedremovetag
	g++ noop.cpp -o noop
	g++ -std=c++11 number.cpp -o number
	g++ -std=c++11 removetag.cpp -o removetag
	g++ -std=c++11 removetag0.cpp -o removetag0

clean:
	rm -rf delayedremovetag.o delayedremovetag
	rm -rf noop.o noopo
	rm -rf number.o number
	rm -rf removetag.o removetag
	rm -rf removetag0.o removetag0
